package com.lyricist.server.utils;

public enum ErrorCodes {
    TOKEN_NOT_VALID,
    MISSING_REQUIRED_HEADERS,
    MISSING_REQUIRED_PARAMS,
    MISSING_REQUIRED_BODY,
    AUTHORIZATION_ERROR,
    CAPTCHA_INVALID,
    INVALID_CREDENTIALS
}
